spring:
  data:
    mongodb:
        database: ProductsDB
        host: localhost
        port: 27017

server:
    validation:
      error:
        include-message: always
        include-binding-errors: always

axon:
  eventhandling:
    processors:
      product-group:
        mode= subscribing