spring:
  data:
    mongodb:
        database: ProductsDB
        host: localhost
        port: 27017

server:
    validation:
      error:
        include-message: always
        include-binding-errors: always

axon:
  processing-group:
    name: product-group
    eventhandling:
        processors:
            product-group:
            mode: subscribing
            source: product-source
            token-store: mongodb
